### ISSUE TITLE
How to use on Vercel

### ISSUE THREAD

**Issue by baptisteArno** [sparanoid/env.sh#1]
Hey friend,

Thank you for all the explanations, that's perfect for a Docker build.

However, how am I supposed to run the script on Vercel? On there I don't use an env file but I add environment variables in the app config.

Because the script is expecting an env file. I'm not sure what I should do exactly? How can I modify the script so that reading from an env file is optional?

**Comment by baptisteArno** [comment]
More globally how can I make the script work without any env file but only runtime injected environment?

**Comment by sparanoid** [comment]
> However, how am I supposed to run the script on Vercel

You can simply follow the README and add your environment variables in project settings on Vercel:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/96356/174655824-25a0c9ad-4327-4397-8292-ef9b7e113c7e.png">

> how can I make the script work without any env file

AFAIK there's no way to do runtime client-side rendering from environment variables without an env file. That's why this project exists.

**Comment by baptisteArno** [comment]
Here is my env function:
```ts
export const env = (key = ''): string | undefined => {
  if (isBrowser() && window.__env) {
    return window.__env[key] === "''" ? undefined : window.__env[key]
  }

  return process.env['NEXT_PUBLIC_' + key] === "''"
    ? undefined
    : (process.env['NEXT_PUBLIC_' + key] as string)
}
```

On Vercel, `window.__env` won't exist so it will look for `process.env['NEXT_PUBLIC_' + key]` but still, it doesn't seem to work, it returns `undefined` anyway.

Not sure what I am doing wrong.

**Comment by baptisteArno** [comment]
Ok, made it work with some tweaks. Thank you @sparanoid 🙏
